In [2]:
import nltk
from nltk import word_tokenize
from nltk.corpus import stopwords

In [1]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [3]:
sentences = nltk.sent_tokenize(paragraph)
stop_words = stopwords.words('english')

In [6]:
# Creating the bag of words
word2count = {}
for sentence in sentences:
    words = nltk.word_tokenize(sentence)
    for word in words:
        if word not in stop_words:
            if word not in stop_words:
                if word not in word2count.keys():
                    word2count[word] = 1
                else:
                    word2count[word] += 1

word2count

{'I': 6,
 'three': 3,
 'visions': 1,
 'India': 5,
 '.': 28,
 'In': 1,
 '3000': 1,
 'years': 2,
 'history': 2,
 ',': 21,
 'people': 1,
 'world': 4,
 'come': 1,
 'invaded': 1,
 'us': 4,
 'captured': 1,
 'lands': 1,
 'conquered': 2,
 'minds': 2,
 'From': 1,
 'Alexander': 1,
 'onwards': 1,
 'Greeks': 1,
 'Turks': 1,
 'Moguls': 1,
 'Portuguese': 1,
 'British': 1,
 'French': 1,
 'Dutch': 1,
 'came': 1,
 'looted': 1,
 'took': 1,
 'Yet': 2,
 'done': 1,
 'nation': 4,
 'We': 5,
 'anyone': 1,
 'grabbed': 1,
 'land': 1,
 'culture': 1,
 'tried': 1,
 'enforce': 1,
 'way': 1,
 'life': 2,
 'Why': 1,
 '?': 2,
 'Because': 2,
 'respect': 3,
 'freedom': 3,
 'others.That': 1,
 'first': 2,
 'vision': 4,
 'believe': 2,
 'got': 1,
 '1857': 1,
 'started': 1,
 'War': 1,
 'Independence': 1,
 'It': 2,
 'must': 4,
 'protect': 1,
 'nurture': 1,
 'build': 1,
 'If': 1,
 'free': 1,
 'one': 2,
 'My': 2,
 'second': 1,
 '’': 2,
 'development': 1,
 'For': 1,
 'fifty': 1,
 'developing': 1,
 'time': 1,
 'see': 3,
 'develope

In [12]:
# creating the vectors from bag of words
import heapq
import numpy as np
freq_words = heapq.nlargest(100, word2count, key=word2count.get)

X = []
for sentence in sentences:
    vector = []
    for word in freq_words:
        if word in nltk.word_tokenize(sentence):
            vector.append(1)
        else:
            vector.append(0)
    X.append(vector)

X = np.asarray(X)

# print the vectors
print(X)

[[1 0 1 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [1 1 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
